name: CI | Build & Test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-docker-and-linux:
    name: Build Docker image & Linux executable
    uses: ./.github/workflows/build-linux-and-docker.yml
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    with:
      output-artifact-name: lottie-to-png.linux.${{ matrix.arch }}
      arch: ${{ matrix.arch }}

  test-docker:
    name: Run tests on Docker
    needs: build-docker-and-linux
    uses: ./.github/workflows/test-docker.yml
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    with:
      output-artifact-name: test-results.linux.${{ matrix.arch }}
      arch: ${{ matrix.arch }}

  build-darwin:
    name: Build Darwin executable
    uses: ./.github/workflows/build-darwin.yml
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    with:
      output-artifact-name: lottie-to-png.darwin.${{ matrix.arch }}
      arch: ${{ matrix.arch }}

  test-darwin:
    name: Test on Darwin
    needs: build-darwin
    uses: ./.github/workflows/test-darwin.yml
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    with:
      input-artifact-name: lottie-to-png.darwin.${{ matrix.arch }}
      output-artifact-name: test-results.darwin.${{ matrix.arch }}
      arch: ${{ matrix.arch }}

  build-windows:
    name: Build Windows executable
    uses: ./.github/workflows/build-windows.yml
    with:
      output-artifact-name: lottie-to-png.windows.amd64.exe

  test-windows:
    name: Test on Windows
    needs: build-windows
    uses: ./.github/workflows/test-windows.yml
    with:
      input-artifact-name: lottie-to-png.windows.amd64.exe
      output-artifact-name: test-results.windows
