name: Test on Darwin

on:
  workflow_call:
    inputs:
      arch:
        description: "amd64 or arm64" 
        required: true
        type: string
      input-artifact-name:
        description: Name of artifact as which Darwin executable is uploaded
        required: true
        type: string
      output-artifact-name:
        description: Name of artifact as which Darwin test results to be uploaded
        required: true
        type: string

permissions:
  contents: read

jobs:
  test-darwin:
    name: Test on Darwin
    runs-on: ${{ inputs.arch == 'arm64' && 'macos-26' || 'macos-15-intel' }}
    strategy:
      matrix:
        case:
          - apng
          - gif
          - png
          - webp
          - webm
        background:
          - ""
          - "rgb(255,255,255)"
          - "#FF0000"
          - "rgba(0,0,255,128)"
    steps:
      - uses: actions/checkout@v7

      - name: Install run-time dependencies
        run: |
          [[ "${{ matrix.case }}" == "apng" ]] && brew install ffmpeg || echo ok;
          [[ "${{ matrix.case }}" == "gif" ]] && brew install gifski || echo ok;
          [[ "${{ matrix.case }}" == "webp" ]] && brew install webp || echo ok;
          [[ "${{ matrix.case }}" == "webm" ]] && brew install ffmpeg || echo ok;

      - name: Download artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: ${{ inputs.input-artifact-name }}
          path: bin

      - name: Run tests
        env:
          BACKGROUND_COLOR: ${{ matrix.background }}
        run: |
          chmod +x bin/lottie_to_png
          find test-files -type f \( -iname \*.json -o -iname \*.lottie -o -iname \*.tgs \) | while IFS=$'\n' read -r FILE; do
            if [ -n "$BACKGROUND_COLOR" ]; then
              echo "Converting ${FILE} with background ${BACKGROUND_COLOR}..." && ./bin/lottie_to_${{ matrix.case }}.sh --background "$BACKGROUND_COLOR" "$FILE" && echo Done.
            else
              echo "Converting ${FILE}..." && ./bin/lottie_to_${{ matrix.case }}.sh "$FILE" && echo Done.
            fi
          done

      - name: Generate background suffix
        id: bg-suffix
        uses: ./.github/actions/background-suffix
        with:
          background: ${{ matrix.background }}

      - name: Upload test results as artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ inputs.output-artifact-name }}.${{ matrix.case }}${{ steps.bg-suffix.outputs.suffix }}
          path: test-files
